version: '3'

services:
  app:
    image: mcr.microsoft.com/devcontainers/universal:2-linux
    volumes:
      - ..:/workspaces/skills-build-applications-w-copilot-agent-mode:cached
    command: sleep infinity
    network_mode: service:mongodb
    
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
      
  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongodb:27017/
    depends_on:
      - mongodb

volumes:
  mongodb-data: